### ISSUE TITLE
渐变没效果

### ISSUE THREAD

**Issue by Kunsan16** [zhongruiAndroid/Ring#1]
RT

**Comment by zhongruiAndroid** [comment]
有按照文档上面的方法设置吗？

**Comment by Kunsan16** [comment]
`LinearGradient linearGradient = new LinearGradient(0,0,
                circleprogress.getWidth(),circleprogress.getHeight(),
                circleprogress.getRingProgressColor(), ContextCompat.getColor(MainActivity.this,R.color.green),
                Shader.TileMode.MIRROR);
        circleprogress.setProgressShader(linearGradient);`

加了这段

**Comment by Kunsan16** [comment]
不好意思，是我获取宽高的问题
我close了
